
const mainMessY = 0
const titlesY = 22
const valuesY = 60


export const UI_CANVAS_WIDGETS_CONFIG = {
    mainMessage: {
        offsetY:  mainMessY,

    },
    titles: [{
        key: 'bet',
        label: 'LINE BET / TOTAL BET',
        x: -259,
        y: titlesY,
        style: 'titlesWidgets',
        widthBack: 375,
     }, {
         key: 'win',
         label: 'WIN',
         x: 155,
         y: titlesY,
         style: 'titlesWidgets',
         widthBack: 180,
     }, {
         key: 'balance',
         label: 'BALANCE',
         x: 360,
         y: titlesY,
         style: 'titlesWidgets',
         widthBack: 180,
     }],
     values: [{
         key: 'lines',
         label: '1.00',
         x: -270 - 70,
         y: valuesY,
         style: 'valuesWidgets',
     }, {
         key: 'bet-sparator',
         label: '/',
         x: -270,
         y: valuesY,
         style: 'valuesWidgets',
     }, {
         key: 'bet',
         label: '500.00',
         x: -270 + 80,
         y: valuesY,
         style: 'valuesWidgets',
     }, {
         key: 'win',
         label: '0.00',
         x: 155,
         y: valuesY,
         style: 'valuesWidgets',
     }, {
         key: 'balance',
         label: '5,000.00',
         x: 360,
         y: valuesY,
         style: 'valuesWidgets',
     }]
 }

 export const UI_CANVAS_CONTROLS_CONFIG = [{
        key: 'menuCanvas',
        maps: ['menuCanvas.png', null, null, null],
        defaultAlpha: 0.8,
        hoverAlpha: 1.0,
        clickAlpha: 0.9,
        scale: 1,
        x: -500,
        y: valuesY,
    }, {
        key: 'infoCanvas',
        maps: ['info.png', null, null, null],
         defaultAlpha: 0.8,
         hoverAlpha: 1.0,
         clickAlpha: 0.9,
        scale: 1,
        x: -500,
        y: valuesY -44,
    }, {
        key: 'perLinesMenuCanvas',
        maps: ['per-lines.png', null, null, null],
         defaultAlpha: 0.8,
         hoverAlpha: 1.0,
         clickAlpha: 0.9,
        scale: 1,
        x: -500,
        y: valuesY -88,
    }, {
        key: 'settingsCanvas',
        maps: ['settings.png', null, null, null],
         defaultAlpha: 0.8,
         hoverAlpha: 1.0,
         clickAlpha: 0.9,
        scale: 1,
        x: -500,
        y: valuesY-132,
    }, {
        key: 'betDownCanvas',
        maps: ['betDownCanvas.png', 'betDownCanvasH.png', null, null],
         defaultAlpha: 0.8,
         hoverAlpha: 1.0,
         clickAlpha: 0.9,
        scale: 1,
        x: -430,
        y: valuesY,
    }, {
        key: 'betUpCanvas',
        maps: ['betUpCanvas.png', 'betUpCanvasH.png', null, null],
         defaultAlpha: 0.8,
         hoverAlpha: 1.0,
         clickAlpha: 0.9,
        scale: 1,
        x: -90,
        y: valuesY,
    }, {
        key: 'spinCanvas',
        maps: ['spinCanvas.png','spinCanvasH.png', null, null],
         defaultAlpha: 0.8,
         hoverAlpha: 1.0,
         clickAlpha: 0.9,
        scale: 1,
        x: 0,
        y: valuesY,
    }, {
        key: 'stopAutoPlay',
        maps: ['spinCanvasNoneStop.png', null, null, null],
         defaultAlpha: 0.8,
         hoverAlpha: 1.0,
         clickAlpha: 0.9,
        scale: 1,
        x: 0,
        y: valuesY,
    }, {
        key: 'stopForce',
        maps: ['spinCanvasForceStop.png', null, null, null],
         defaultAlpha: 0.8,
         hoverAlpha: 1.0,
         clickAlpha: 0.9,
        scale: 1,
        x: 0,
        y: valuesY,
    }, {
        key: 'soundOffCanvas',
        maps: ['soundOn.png', null, null, null],
         defaultAlpha: 0.8,
         hoverAlpha: 1.0,
         clickAlpha: 0.9,
        scale: 1,
        x: 555,
        y: valuesY,
    }, {
        key: 'soundOnCanvas',
        maps: ['soundOff.png', null, null, null],
         defaultAlpha: 0.8,
         hoverAlpha: 1.0,
         clickAlpha: 0.9,
        scale: 1,
        x: 555,
        y: valuesY,
    }, {
        key: 'homeCanvas',
        maps: ['homeCanvas.png', null, null, null],
         defaultAlpha: 0.8,
         hoverAlpha: 1.0,
         clickAlpha: 0.9,
        scale: 1,
        x: 500,
        y: valuesY,
    },
]

